#!/bin/sh

# Define a separator for better log visibility
separator="============================"

echo "$separator"
echo "Running Prettier for code formatting..."
npm run format
if [ $? -ne 0 ]; then
    echo "Error: Code formatting failed."
    exit 1
fi

git add .

echo "$separator"
echo "Running ESLint for code linting..."
# Run ESLint without the --fix option
npm run lint
if [ $? -ne 0 ]; then
    echo "Error: Linting failed. Please fix the issues before committing."
    exit 1
fi

git add .

echo "$separator"
echo "All pre-commit checks passed successfully!"
